# Generated by Django 5.0.2 on 2024-03-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.IntegerField(max_length=5, unique=True)),
                ('switch', models.IntegerField(max_length=5)),
                ('src', models.GenericIPAddressField(protocol='IPv4')),
                ('dst', models.GenericIPAddressField(protocol='IPv4')),
                ('pktcount', models.IntegerField(max_length=5)),
                ('bytecount', models.IntegerField(max_length=5)),
                ('dur', models.IntegerField(max_length=5)),
                ('dur_nsec', models.IntegerField(max_length=5)),
                ('tot_dur', models.IntegerField(max_length=5)),
                ('flows', models.IntegerField(max_length=5)),
                ('pachetins', models.IntegerField(max_length=5)),
                ('pktperflow', models.IntegerField(max_length=5)),
                ('byteperflow', models.IntegerField(max_length=5)),
                ('pktrate', models.IntegerField(max_length=5)),
                ('Pairflow', models.IntegerField(max_length=5)),
                ('Protocol', models.CharField(max_length=5)),
                ('port_no', models.IntegerField(max_length=5)),
                ('tx_bytes', models.IntegerField(max_length=5)),
                ('rx_bytes', models.IntegerField(max_length=5)),
                ('tx_kbps', models.IntegerField(max_length=5)),
                ('rx_kbps', models.IntegerField(max_length=5)),
                ('tot_kbps', models.IntegerField(max_length=5)),
                ('label', models.IntegerField(max_length=5)),
            ],
        ),
    ]
