# Generated by Django 5.0.2 on 2024-03-28 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.IntegerField()),
                ('switch', models.IntegerField()),
                ('src', models.GenericIPAddressField(protocol='IPv4')),
                ('dst', models.GenericIPAddressField(protocol='IPv4')),
                ('pktcount', models.IntegerField()),
                ('bytecount', models.IntegerField()),
                ('dur', models.IntegerField()),
                ('dur_nsec', models.IntegerField()),
                ('tot_dur', models.IntegerField()),
                ('flows', models.IntegerField()),
                ('packetins', models.IntegerField()),
                ('pktperflow', models.IntegerField()),
                ('byteperflow', models.IntegerField()),
                ('pktrate', models.IntegerField()),
                ('Pairflow', models.IntegerField()),
                ('Protocol', models.CharField(max_length=5)),
                ('port_no', models.IntegerField()),
                ('tx_bytes', models.IntegerField()),
                ('rx_bytes', models.IntegerField()),
                ('tx_kbps', models.IntegerField()),
                ('rx_kbps', models.IntegerField()),
                ('tot_kbps', models.IntegerField()),
                ('label', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPcap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(max_length=10)),
                ('dst_ip', models.CharField(max_length=10)),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('protocol', models.IntegerField()),
                ('Label', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
    ]
