# Generated by Django 5.0.2 on 2024-03-04 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networktraffic',
            name='username',
            field=models.ForeignKey(default=132, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='Pairflow',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='bytecount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='byteperflow',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='dt',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='dur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='dur_nsec',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='flows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='label',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='pachetins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='pktcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='pktperflow',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='pktrate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='port_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='rx_bytes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='rx_kbps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='switch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='tot_dur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='tot_kbps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='tx_bytes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='tx_kbps',
            field=models.IntegerField(),
        ),
    ]
