# Generated by Django 5.0.2 on 2024-03-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_networktraffic_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networktraffic',
            name='username',
        ),
    ]
