# Generated by Django 5.0.2 on 2024-03-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_networktraffic_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networktraffic',
            old_name='pachetins',
            new_name='packetins',
        ),
    ]
