# Generated by Django 5.0.2 on 2024-03-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_pachetins_networktraffic_packetins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networktraffic',
            name='dt',
            field=models.IntegerField(),
        ),
    ]
